export enum EventTypes {
    UP = 'UP',
    DOWN = 'DOWN',
    LEFT = 'LEFT',
    RIGHT = 'RIGHT',
    ADD = 'ADD',
    DELETE = 'DELETE',
    CANCEL = 'CANCEL',
    EDIT_FIELD = 'EDIT_FIELD',
    EDIT_DEFAULT_VALUE = 'EDIT_DEFAULT_VALUE',

    REACT_WITH_UP = 'REACT_WITH_UP',
    REACT_WITH_DOWN = 'REACT_WITH_DOWN',
    REACT_WITH_LEFT = 'REACT_WITH_LEFT',
    REACT_WITH_RIGHT = 'REACT_WITH_RIGHT',
    REACT_WITH_ADD = 'REACT_WITH_ADD',
    REACT_WITH_DELETE = 'REACT_WITH_DELETE',
    REACT_WITH_CANCEL = 'REACT_WITH_CANCEL',
    REACT_WITH_EDIT_FIELD = 'REACT_WITH_EDIT_FIELD',
    REACT_WITH_EDIT_DEFAULT_VALUE = 'REACT_WITH_EDIT_DEFAULT_VALUE',
    REACT_WITH_CONFIRM = 'REACT_WITH_CONFIRM',
    REACT_WITH_CLICK = 'REACT_WITH_CLICK'
}